### PR TITLE
Remove preview docker images when closing PR

### LINKED ISSUE #14: Remove docker images from docker image registry when closing PR
ghcr.io

### PR DESCRIPTION
**Pull request by thomastvedt**
Closes #14 

We're using GHCR - Github container registry which is currently in beta. I was planning to delete images using Github GraphQL API, but this is not supported yet by GHCR 😞 

Delete container image (ghcr beta): https://docs.github.com/en/packages/guides/deleting-a-container-image

Quote:
```
You can remove an entire container image or a specific version on GitHub.   
To delete a container image, you must use the UI. Using  
GraphQL to delete a container image is not supported at this time.

To delete a container image, you must have admin permissions to the container image.

When deleting public packages, be aware that you may break projects that depend on your package.
```

No packages returned by Github API:
image

One last thing to try:
can we use standard docker commands to delete image?

=> nope...

Apparently this feature is coming soon, hopefully by the end of (last) month? 😉
  
https://github.community/t/are-there-plans-to-support-deletions-of-images-in-ghcr/153728

`But we’re working on a delete API that could be used on PR merge. Hoping to have this out by end of month.`

@ralftar : 
I guess we'll just have to wait for this feature to be released? Or switch to another package registry? Or try to "hack it" using the same http requests as the Github UI (but I want to wait..)

### CODE REVIEW

**Comment by ralftar** [comment]
We'll wait 👍

**Comment by thomastvedt** [comment]
Update:
this is now released-ish..

See this action for deleting packages:
https://github.com/marketplace/actions/delete-package-versions
but that is marked as unmaintained..: https://github.com/actions/delete-package-versions/issues/36

Also it doesn't support deleting docker images:
https://github.com/actions/delete-package-versions/issues/35

Perhaps this one is worth checking out?:
https://github.com/SmartsquareGmbH/delete-old-packages/issues/5

**Comment by thomastvedt** [comment]
https://github.com/marketplace/actions/delete-a-package

**Comment by thomastvedt** [comment]
https://github.com/marketplace?type=actions&query=delete+package

**Comment by nikeee** [comment]
I'm facing the same problem and I'l probably use this:
https://github.com/marketplace/actions/delete-untagged-containers

Found via:
https://github.com/marketplace?type=actions&query=delete+container

**Comment by thomastvedt** [comment]
https://github.com/marketplace/actions/ghcr-delete-image

test this one?

**Pull request closed without merging**
