### PR TITLE
deploy-preview: Update helm version

### LINKED ISSUE #228: Use latest version of helm
https://github.com/vendanor/preview-pull-request/blob/06fd30cb63834c8c1a4ceabed1ec0d76bcaf26e8/src/deploy-preview.ts#L55-L57

now resolved?

### PR DESCRIPTION
**Pull request by jonaski**
Fixes #228

### CODE REVIEW

**Review by ralftar — APPROVED** [review]
For me this is OK, @thomastvedt has to decide.

**Comment by jonaski** [comment]
There is no CI here, how do we test this? I'm a JavaScript n00b.

**Comment by ralftar** [comment]
Non technical person, huh? 🍸 `npn run all` should do the trick. You need node installed.

**Comment by ralftar** [comment]
The compiled js code needs to be committed when the action is typescript 😶

**Comment by thomastvedt** [comment]
> The compiled js code needs to be committed when the action is typescript 😶

That is correct. When GitHub runs the action it checks out the preview repo and runs the transpiled JavaScript files. I guess this is why many GitHub actions use pure JavaScript and not TypeScript..

TODO:
npm run all
git commit

**Pull request merged**
